# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewWindow(object):
    def setupUi(self, NewWindow):
        NewWindow.setObjectName("NewWindow")
        NewWindow.resize(554, 449)
        self.centralwidget = QtWidgets.QWidget(NewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(20, 10, 21, 16))
        self.label_id.setObjectName("label_id")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(50, 10, 31, 21))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.pushButton11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton11.setGeometry(QtCore.QRect(100, 10, 171, 23))
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton12.setGeometry(QtCore.QRect(330, 10, 191, 23))
        self.pushButton12.setObjectName("pushButton12")
        self.tableWidget11 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget11.setGeometry(QtCore.QRect(20, 60, 511, 192))
        self.tableWidget11.setObjectName("tableWidget11")
        self.tableWidget11.setColumnCount(0)
        self.tableWidget11.setRowCount(0)
        self.label_zap1 = QtWidgets.QLabel(self.centralwidget)
        self.label_zap1.setGeometry(QtCore.QRect(80, 270, 391, 21))
        self.label_zap1.setObjectName("label_zap1")
        self.label_zap2 = QtWidgets.QLabel(self.centralwidget)
        self.label_zap2.setGeometry(QtCore.QRect(30, 300, 501, 20))
        self.label_zap2.setObjectName("label_zap2")
        self.lineEdit_zap = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_zap.setGeometry(QtCore.QRect(30, 340, 501, 20))
        self.lineEdit_zap.setObjectName("lineEdit_zap")
        self.pushButton_zap = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zap.setGeometry(QtCore.QRect(190, 380, 141, 23))
        self.pushButton_zap.setObjectName("pushButton_zap")
        NewWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NewWindow)
        self.statusbar.setObjectName("statusbar")
        NewWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NewWindow)
        QtCore.QMetaObject.connectSlotsByName(NewWindow)

    def retranslateUi(self, NewWindow):
        _translate = QtCore.QCoreApplication.translate
        NewWindow.setWindowTitle(_translate("NewWindow", "MainW"))
        self.label_id.setText(_translate("NewWindow", "ID:"))
        self.pushButton11.setText(_translate("NewWindow", "Получить данные по ID"))
        self.pushButton12.setText(_translate("NewWindow", "Изменить данные"))
        self.label_zap1.setText(_translate("NewWindow", "Для добавления новых данных, введите необхлдиме данные через пробел"))
        self.label_zap2.setText(_translate("NewWindow", "Название сорта, степень обжарки, молотый/в зернах, описание вкуса, цена, объем упаковки"))
        self.pushButton_zap.setText(_translate("NewWindow", "Добавить данные в БД"))
